id: P004503
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG17576
  title: རྡོ་རྗེ་རྣལ་འབྱོར་མའི་དཀྱིལ་འཁོར་སྒྲུབ་མཆོད་འགྲོ་ཀུན་མཁའ་སྤྱོད་བགྲོད་པའི་མྱུར་ལམ།
  author: ''
  volumes:
    dce92462a82249d2b2f0b5a93d244cff:
      image_group_id: I1KG17936
      title: ''
      volume_number: 1
      total_pages: 122
      base_file: v001.txt
