id: I6209E19D
legacy_id: P004503
ocr_import_info:
  bdrc_scan_id: W1KG17576
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T07:40:57'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T09:39:08.805697+00:00'
last_modified: 2022-08-31 17:39:15.730885
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG17576
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG17576
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྡོ་རྗེ་རྣལ་འབྱོར་མའི་དཀྱིལ་འཁོར་སྒྲུབ་མཆོད་འགྲོ་ཀུན་མཁའ་སྤྱོད་བགྲོད་པའི་མྱུར་ལམ།
  author: མཁྱེན་བརྩེའི་དབང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.8882407871192719
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I1KG17936:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17936
      total_pages: 122
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG17936.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8882407871192719
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
